# Numpy 기초연습문제

In [2]:
import numpy as np #numpy 모듈 콜링

## 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [3]:
a = np.zeros((3, 4)) #행이 3개, 열이 4개인 array 생성 후 출력
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [4]:
for i in range(a.shape[0]): # a의 행의수 3 range의 인수에 할당.
    for j in range(a.shape[1]): # a의 열의수 4 range의 인수에 할당.
        a[i, j] = i*4 + j + 1 # 배열 a의 값을 식을 활용해 1부터 12까지 값 할당.
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [5]:
num = 1
for i in range(a.shape[0]): # a의 행의수 3 range의 인수에 할당.
    for j in range(a.shape[1]): # a의 열의수 4 range의 인수에 할당.
        a[i, j] =  num 
        num += 1 # a의 값을 num 변수를 활용한 식을 활용해 1부터 12까지 값 할당.
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

## 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [6]:
a[1, 2] # a의 2번째 행 3번째 열 출력.

7.0

## 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.
array([[5., 6., 7., 8.]])

In [7]:
a.shape # a가 몇차원의 행렬인지 출력.

(3, 4)

In [8]:
a[[1], :] # a의 두번째 행 값 전부 출력.

array([[5., 6., 7., 8.]])

## 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.
array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

In [22]:
a[:,[1, 2]] # a의 2열과 3열의 값을 출력

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

## 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리한 인덱싱을 하시오.
array([1., 2., 3., 4., 5., 6.])

In [23]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result
# array result의 값을 a[i,j]의 값으로 지정한다.
# a[i.j]값은 a의 데이터 중 if a[i,j] <=6을 만족하는 조건을 가진다.
# result 출력시 6 이하의 값이 출력된다.

array([1., 2., 3., 4., 5., 6.])

In [14]:
a[a <= 6] # a의 값중 6보다 작거나 같은 값을 전부 추출한다.

array([1., 2., 3., 4., 5., 6.])

## 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [15]:
b = np.random.random((3, 4))
b # np.random 패키지의 random 메소드를 활용해 주어진 조건인 3행 4열의 array를 0과 1 사이의 무작위 값으로 만들 수 있음.

array([[0.72088462, 0.92634562, 0.6680508 , 0.6761856 ],
       [0.89280126, 0.1762488 , 0.87715647, 0.1334387 ],
       [0.8426851 , 0.8600743 , 0.88581375, 0.78457789]])

## 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [16]:
c = a * b
c # array a와 b끼리 곱셈.

array([[0.72088462, 1.85269124, 2.00415241, 2.70474239],
       [4.46400629, 1.0574928 , 6.14009527, 1.06750964],
       [7.58416593, 8.60074298, 9.74395129, 9.4149347 ]])

## 9. b의 전치행렬을 구하여 d에 저장하시오.

In [17]:
d = b.T
d # T메소드를 활용해 b의 행과 열을 뒤바꾼 d 전치행렬 생성.

array([[0.72088462, 0.89280126, 0.8426851 ],
       [0.92634562, 0.1762488 , 0.8600743 ],
       [0.6680508 , 0.87715647, 0.88581375],
       [0.6761856 , 0.1334387 , 0.78457789]])

In [18]:
d.shape # d의 차원 출력

(4, 3)

## 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [19]:
print(a.shape, d.shape) #a와 d의 각 차원의 크기 출력

(3, 4) (4, 3)


## 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [20]:
e = a.dot(d) # dot메소드 활용해 a와 d의 행렬 곱의 값을 e에 저장.
e

array([[ 7.28247066,  4.41052308,  8.35858652],
       [19.24833722, 12.72910399, 21.85119071],
       [31.21420379, 21.04768491, 35.34379489]])

## 12. e에 대하여 각 열의 합을 계산하시오.

In [24]:
np.sum(e, axis=0) # axis 파라미터를 0으로 지정해 행렬 e를 열방향으로 더한 값을 출력.

array([57.74501167, 38.18731198, 65.55357213])